language: node_js
sudo: false
git:
  depth: 10

node_js:
  - "4"
  - "6"
  - "8"
  - "10"

install:
  - cd ..
  - git clone https://github.com/apache/cordova-android --depth 10
  - git clone https://github.com/apache/cordova-ios --depth 10
  - git clone https://github.com/apache/cordova-blackberry --depth 10
  - git clone https://github.com/apache/cordova-windows --depth 10
  - git clone https://github.com/apache/cordova-wp8 --depth 10
  - git clone https://github.com/apache/cordova-firefoxos --depth 10
  - git clone https://github.com/apache/cordova-ubuntu --depth 10
  - git clone https://github.com/apache/cordova-browser --depth 10
  - git clone https://github.com/apache/cordova-amazon-fireos --depth 10
  - git clone https://github.com/apache/cordova-webos --depth 10
  - cd cordova-js
  - npm install
