language: node_js
sudo: false
git:
  depth: 10

node_js:
  - "8"
  - "10"

install:
  - cd ..
  - git clone https://github.com/apache/cordova-android --depth 10
  - git clone https://github.com/apache/cordova-ios --depth 10
  - git clone https://github.com/apache/cordova-windows --depth 10
  - git clone https://github.com/apache/cordova-browser --depth 10
  - cd cordova-js
  - npm install
